### ISSUE TITLE
Repeating query parameters 

### ISSUE THREAD

**Issue by lorszi456** [basdijkstra/rest-assured-net#105]
I have a Map<String, Object> of parameters. Some of these parameters have lists and rest assured will set the parameter value as a comma separated list:

http://url.com/rest?field1=value&fieldlist=1,2,3

I am using jersey and for some reason it doesn't accept these CSV lists. It tried to the parameter lists with repeating values but not working because use the lase query parameters:

Code: .
Given().QueryParam("fieldlist", "1")..QueryParam("fieldlist", "2").queryParam("fieldlist", "3") .
http://url.com/rest?field1=value&fieldlist=3

Is there a way I can configure  lists or repeating values?

In java working this:
given().queryParam("fieldlist", "1", "2", "3"). .

**Comment by basdijkstra** [comment]
Hey @lorszi456, you're right, at the moment there's no support for multi-value query parameters in RestAssured .Net. As you've seen, only the last supplied value is used. That's because internally, the list of query parameters is stored as a `Dictionary<string, string>`, and values supplied earlier are simply overwritten.

Doing a quick Google search shows there are two ways to supply these, depending on the implementation of the API:

* `http://some.url?fieldlist=1&fieldlist=2&fieldlist=3`
* `http://some.url?fieldlist=1,2,3`

I would like to be able to support them both at some point, but right now, let's focus on the second option which is the one you're looking for.

A simple way to get the result you're looking for is to do this:

`QueryParam("fieldlist", "1,2,3")`

but that means you'll need to do the concatenation yourself.

I'm happy to implement an overload that allows you to do this:

`QueryParam("fieldlist", "1", "2", "3")`

Would that be helpful?

**Comment by lorszi456** [comment]
Development sounds good. I would need both versions during testing. But I would use the second version in more places. So that one: 
QueryParam("fieldlist", "1", "2", "3")

Thank you very much in advance

**Comment by basdijkstra** [comment]
Hey @lorszi456, I've added support for this format:

http://some.url?fieldlist=1,2,3

Here's an example test that shows how to use it: https://github.com/basdijkstra/rest-assured-net/blob/f4a4c7de0bcefc77f928340ece871c1e31c48c9d/RestAssured.Net.Tests/QueryParameterTests.cs#L133

If you want to test it for yourself, I've just published `4.1.0-beta.1`: https://www.nuget.org/packages/RestAssured.Net/4.1.0-beta.1

Please let me know if it works and if there's anything else you need.

**Comment by lorszi456** [comment]
Thank you very much, this version works. I just need the other one. 
QueryParam("fieldlist", "1", "2", "3")

I really appreciate the quick response.

**Comment by basdijkstra** [comment]
And by 'the other one' you mean the ability to render the endpoint like this:

http://some.url?fieldlist=1&fieldlist=2&fieldlist=3

Is that correct? That might take a bit more work, but I'll start thinking about how to easily implement that, too.

**Comment by lorszi456** [comment]
Yes that one. Thanks.

**Comment by basdijkstra** [comment]
So, while this seems very straightforward, implementing it cleanly isn't as easy as it looks.

First of all, I need to change the way query parameters are stored internally from a `Dictionary<string, string>` to an `IEnumerable<KeyValuePair<string, string>>` to be able to store multiple query parameters with the same name.

That's doable (in fact, I'm nearly there).

The difficult part is how to decide which of the two URL building strategies to use, so to decide between

* `http://some.url?field=1&field=2`, and
* `http://some.url?field=1,2`

I'm tempted to default to `http://some.url?field=1&field=2` when you supply multiple query parameter values like using

`QueryParam("field", 1, 2)`

In that way, you can still get the second one yourself by calling it like this:

`QueryParam("field", string.Join(",", <some list>))`

Why default to the first? Because that's what I see in most documentation examples on the web.

@lorszi456 what do you say?

**Comment by lorszi456** [comment]
I agree with you, I think you should use the first url format by default, that is:

- http://some.url?field=1&field=2

I have worked on several projects and we used this format and we are still using it. I also searched a bit and found the most with this format as well.

**Comment by basdijkstra** [comment]
Thank you for the feedback, I’ll change the implementation to support that format then.

Again, you would still be able to provide values in the comma-separated format quite easily (and I’ll include a test to make sure that works).

**Comment by basdijkstra** [comment]
I think I'm nearly there, I'm just waiting for an answer to a question on how to work with comma-separated values for query parameters in the HTTP mocking library I'm using in the project.

I can see the requests are made as expected, so I expect to be able to create a new beta with what should be the final implementation soon.

**Comment by basdijkstra** [comment]
@lorszi456 I've gone ahead and published a new beta version, which now defaults to converting

`QueryParam("field", 1, 2, 3)`

to

`http://some.url?field=1&field=2&field=3`

As said, you can still specify comma-separated values like this:

`QueryParam("fieldlist", string.Join(",", 1, 2, 3))`

which results in

`http://some.url?fieldlist=1,2,3`

Could you please test this version and see if it works as you would expect?

https://www.nuget.org/packages/RestAssured.Net/4.1.0-beta.2

Thanks!

**Comment by lorszi456** [comment]
Thank you so much. This version is works for me perfectly. :)

`            HttpResponseMessage response = Given()
                .Spec(requestSpecification)
                .QueryParam("branchId", branchId)
                .QueryParam("lineId", lineId)
                .QueryParam("from", from)
                .QueryParam("to", to)
                .QueryParam("freeTextFilter", "")
                .QueryParam("states", 1, 8, 7, 9, 2)
                .QueryParam("maxRecordCount", 1000)
                .When()
                .Get(url + GetAllAppointmentPath)
                .Then()
                .StatusCode(200)
                .Extract().Response();`
`GET https://url/path?branch=1&line=2&from=2023-08-12&to=2023-08-26&freeTextFilter=&states=1&states=8&states=7&states=9&states=2&maxRecordCount=1000`

I really appreciate the quick response

**Comment by basdijkstra** [comment]
Thank you too for your quick reaction and for reporting this issue. I’ll release this in version 4.1.0, but of course you can keep using the beta for now.

Closing this one now, feel free to reopen it or open a new issue if there’s anything else you’re missing.
