### ISSUE TITLE
Question: How many threads can there be by default?

### ISSUE THREAD

**Issue by workmichsem** [basdijkstra/rest-assured-net#108]
Hi
Does RestAssured have a limit on the number of threads?
If so, how is it installed and what is the default?

Also a question about the maximum waiting time for a request to be completed.
What is it like? How can I set a different value?

**Comment by workmichsem** [comment]
There is one more question
Can I see the response size in kilobytes?

**Comment by basdijkstra** [comment]
Hey @workmichsem,

regarding the maximum number of connections: since I'm using `Sytem.Net.Http.HttpClient` under the hood, this is probably the default value for `System.Net.Http.HttpClientHandler.MaxConnectionsPerServer`, which defaults to `int.MaxValue`: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver?view=net-7.0

This might change due to #107, but I haven't had the time to work on that yet.

The maximum waiting time, or rather the `HttpClient` timeout, defaults to 100 seconds, but can be changed: https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#timeouts

The response size in bytes can typically be found in the `Content-Length` header of the response. You can write a verification against it: https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#response-body-length (this uses the actual response body length, by the way, not the value of the `Content-Length` header). You can also calculate the length yourself by extracting the response body as a `string` and calculating its value. See also #92.

Hope that helps, if not, feel free to ask :)

**Comment by workmichsem** [comment]
Thank you very much for your answers!

Regarding the number of threads. So there is no way to change this value now? If not, will it be possible in the future?

**Comment by basdijkstra** [comment]
No, there is no way to change this at the moment. What is your use case for this? It shouldn't be too hard to add a method to configure this, but I'm curious to see why you would need it.

Also, once I start working on #107 this might become possible, too.

**Comment by workmichsem** [comment]
Just trying to understand what the limitations are
Thank you very much for the information

**Comment by basdijkstra** [comment]
No problem!

I just remembered something: you _can_ configure the maximum number of connections yourself by injecting an `HttpClient` of your own and configuring the `MaxConnectionsPerServer` property on the `HttpClientHandler` associated with the client.

See https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#using-a-custom-httpclient

If this is enough information for you, please close the issue. If not, leave it open and ask away :)
