### ISSUE TITLE
ResponseLogLevel cannot be overridden at a response level

### ISSUE THREAD

**Issue by sqh-jack-starkey** [basdijkstra/rest-assured-net#128]
Hey,

We're using the ability to set the Request and Response by default on all tests to `All` using the static configuration in the Dsl class, e.g. 
``` 
RestAssuredConfig = new RestAssuredConfiguration
{
    RequestLogLevel = RequestLogLevel.All,
    ResponseLogLevel = ResponseLogLevel.All
};
```
However for some tests we don't want to log everything, or we want to pass in sensitive headers. 
So we are attempting to configure logging per test e.g.:
```
 .Log(ResponseLogLevel.None)
```
This works for the request logging, but not response logging.

It seems we have already logged the response by the time we get the VerifiableResponse back, so when calling `Log` this has no effect. (https://github.com/basdijkstra/rest-assured-net/blob/8f3a46635ae3a702f8ad4f5e9a4292dcdd25747f/RestAssured.Net/Request/ExecutableRequest.cs#L676)

Could you confirm if my thinking is correct, or if there are any other ways we could do this please? 
Alternatively I am happy to contribute if you point me in the direction you'd want to take to implement this.

Thanks,
Jack

**Comment by basdijkstra** [comment]
Hey @sqh-jack-starkey, thank you for reporting this. Let me have a good look at it in the next couple of days and see what I can do. It might just be just a matter of incorrect priorities when setting the response log level but I’ll have to dive into that. I’ll get back to you somewhere next week if that’s OK.

**Comment by sqh-jack-starkey** [comment]
That's great thank you

**Comment by basdijkstra** [comment]
So, @sqh-jack-starkey, I can reproduce the bug on my machine, that's a good thing. The problem is I'm calling the `Log()` on the response internally here: https://github.com/basdijkstra/rest-assured-net/blob/8f3a46635ae3a702f8ad4f5e9a4292dcdd25747f/RestAssured.Net/Request/ExecutableRequest.cs#L676

using the `ResponseLogLevel` value from the configuration / a `RequestSpecification`. Then, the `Log()` method is called again when you add it yourself, leading to duplicated logging. You haven't seen this because you set the `ResponseLogLevel` to `None`, but change that to `ResponseTime` for example and you'll see logging that looks like this (the last three lines is what you should be looking for:

```
HTTP 200 (OK)
Content-Type: application/json
Content-Length: 198
Date: Sun, 06 Oct 2024 07:06:34 GMT
Server: Kestrel
Transfer-Encoding: chunked
{
  "Country": "United States",
  "State": "California",
  "ZipCode": 90210,
  "Places": [
    {
      "Name": "Sun City",
      "Inhabitants": 100000,
      "IsCapital": true
    },
    {
      "Name": "Pleasure Meadow",
      "Inhabitants": 50000,
      "IsCapital": false
    }
  ]
}
Response time: 130,0303 ms
HTTP 200 (OK)
Response time: 130,0303 ms
```

That's not good :)

What I think needs to change is:
* Instead of logging the response immediately, I should add the value set in the configuration or `RequestSpecification` as a property when I create a `VerifiableResponse`
* That value should then be overridden by a call to `Log()` on the `VerifiableResponse`
* The actual logging should happen only when the `VerifiableResponse` is disposed to make sure it is called exactly once, because logging still needs to happen even when you don't call `Log()` explicitly on the response

Am I missing something here? I haven't gone ahead and actually built and tested this yet, wanted to hear your thoughts first, I'll find some time during the week to work on this.

**Comment by sqh-jack-starkey** [comment]
Yeah that looks right, I’ve just tried with different logging level and I am getting the same behaviour. 

What you’ve suggested sounds like it would resolve the issue. 

Another workaround (for our problem anyway), would be to add `ResponseLogLevel` to the `RequestSpecification` so that we could override the static config by passing a different specification before the request is executed and response logged. 

Thanks for looking into this btw, you’ve already saved us loads of time just by writing this library. We’ve got 1000+ tests in our suite and only just getting started.

**Comment by basdijkstra** [comment]
Workarounds are good but I prefer solutions :) Excellent, I’ll try and get some work done on that this coming week.

Hearing you get so much good use out of the library makes my day by the way! I’d love to see it in action one day if you’re willing and able to share.

**Comment by basdijkstra** [comment]
Hmm, so the approach I thought of doesn't work because `Dispose()` isn't automatically called and I can't predict when the test is 'done' (i.e., there will no more calls to `Log()`). I'll have to rethink this, suggestions are welcome :)

**Comment by sqh-jack-starkey** [comment]
Only thing I can think of is to move the response log method to before the execution of the request. e.g. set the request and response logging at the same time (I believe the Java implementation does it this way)

Obviously that would be a breaking change though.

**Comment by basdijkstra** [comment]
@sqh-jack-starkey just spent another couple of hours breaking my head over how to fix this, but I can't think of anything at the moment. Any suggestions highly welcomed, preferably one that doesn't require a breaking change..

**Comment by basdijkstra** [comment]
@sqh-jack-starkey I've decided to introduce the breaking change, i.e., I'm going to move the specification of the response log level to the `Given()` section. It will simplify the logging logic, too, which is a nice added bonus.

I'll add that to the next release (including deprecating the current methods), which is due to come out soon anyway because I want to add support for .NET 9, too. This means everyone can start moving their `Log()` statements to the new place without breaking any existing code yet.

Thank you for thinking along here. I appreciate it. I'll add another comment when this new version released so you can confirm that it now works as expected.

**Comment by basdijkstra** [comment]
Addressed in https://github.com/basdijkstra/rest-assured-net/commit/a83796fbd5ca22c846f28c6b320b92233008781a.

@sqh-jack-starkey, I'm releasing 4.5.0 in a couple of minutes, could you please test this by using the new `Log()` method that takes a `LogConfiguration` (and update your `RequestSpecification` or static RestAssured configuration and let me know if that addresses your logging issues?

Please remove all references to obsolete `Log()` methods to make sure you don't get duplicate logging.

**Comment by sqh-jack-starkey** [comment]
Will do, thank you!

**Comment by basdijkstra** [comment]
It's live, @sqh-jack-starkey: https://www.nuget.org/packages/RestAssured.Net/4.5.0

All feedback welcome. Working on the docs now, but the `LoggingTests` contain plenty of examples.

**Comment by basdijkstra** [comment]
Found a small bug in the new logging logic, fixed in 4.5.1: #131.

**Comment by sqh-jack-starkey** [comment]
@basdijkstra Tested this today and it's working perfectly for our use case. Thank you!

**Comment by basdijkstra** [comment]
You're welcome, @sqh-jack-starkey! Thanks for the feedback.
