### ISSUE TITLE
Maybe replace Stubble by Handlebars.Net

### ISSUE THREAD

**Issue by StefH** [basdijkstra/rest-assured-net#2]
Just an idea : replace Stubble by Handlebars.Net ?

(disclaimer : I'm using Handlebars.Net & Scriban and I don't know Stubble at all...)

**Comment by basdijkstra** [comment]
I’ll have a look, but so far Stubble has been really easy to use. Thank you for the suggestion, though.

**Comment by basdijkstra** [comment]
@StefH I've looked into this and it seems like both libraries essentially do the same thing. Since Stubble is a reasonably active project, and I'm really only using its string rendering capability for replacing path parameter templates, I think it's safe to leave it like it is.

I appreciate the suggestion, though, gives me an alternative to check out in case Stubble doesn't live up to the expectations anymore.

Are you OK with me closing this?

**Comment by StefH** [comment]
Ok

**Comment by basdijkstra** [comment]
Closed with thanks for the suggestion.
